### ISSUE TITLE
i can't get any data

### ISSUE THREAD

**Issue by lateautumnlin** [ringtail/lucas#2]

**Comment by ringtail** [comment]
证书配置是否正确

**Comment by ringtail** [comment]
@lateautumnlin

**Comment by lateautumnlin** [comment]
我查看这个容器的log记录，是这样写的
```

2018/12/12 11:26:56 http: panic serving 10.60.118.172:33228: runtime error: invalid memory address or nil pointer dereference

```

**Comment by ringtail** [comment]
@lateautumnlin 应该是证书使用的不对，不应该用peer的证书，应该用client的证书。另外ENDPOINTS中要写https://127.0.0.1:2379

**Comment by lateautumnlin** [comment]
因为我是用kubeadm直接启动的容器，而且etcd也是有kubeadm启动的pod，所以，应该是不存在client的证书，在/etc/kubernetes/pki/etcd的目录下是只有
```

-rw-r--r--. 1 root root 1017 Nov 28 06:59 ca.crt
-rw-------. 1 root root 1679 Nov 28 06:59 ca.key
-rw-r--r--. 1 root root 1094 Nov 28 06:59 healthcheck-client.crt
-rw-------. 1 root root 1679 Nov 28 06:59 healthcheck-client.key
-rw-r--r--. 1 root root 1127 Nov 28 06:59 peer.crt
-rw-------. 1 root root 1675 Nov 28 06:59 peer.key
-rw-r--r--. 1 root root 1119 Nov 28 06:59 server.crt
-rw-------. 1 root root 1679 Nov 28 06:59 server.key

```
不知道 该怎么 处理，之前看了https://jimmysong.io/kubernetes-handbook/guide/using-etcdctl-to-access-kubernetes-data.html的博客，是可以使用peer的证书来做访问，所以我就直接用这个来访问，可是还是不行

**Comment by ringtail** [comment]
@lateautumnlin 这个证书用etcdctl是可以直接到后端的是吗，如果可以，试下加下Endpoints中加下https

**Comment by lateautumnlin** [comment]
对，我在etcd 的pod中是这样使用的
```

etcdctl --cacert=/etc/kubernetes/pki/etcd/ca.crt \
--cert=/etc/kubernetes/pki/etcd/peer.crt \
--key=/etc/kubernetes/pki/etcd/peer.key \
get /registry/namespaces/default -w=json
```
这样是可以获取到数据的，
我试了一下使用https的方式，如下：
```
docker run -d -p 8088:8080  -v /etc/kubernetes/pki/etcd/:/etc/kubernetes/pki/etcd/ 
-e CA_FILE=/etc/kubernetes/pki/etcd/ca.crt 
-e CERT_FILE=/etc/kubernetes/pki/etcd/server.crt 
-e KEY_FILE=/etc/kubernetes/pki/etcd/server.key  
-e ENDPOINTS="https://127.0.0.1:2379" 
registry.cn-hangzhou.aliyuncs.com/ringtail/lucas:0.0.1

```
这样的话效果是一样的，访问不到

docker logs 里面的报错是这样的
```

goroutine 87 [running]:
net/http.(*conn).serve.func1(0xc42023a0a0)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x91d960, 0xca5f80)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/ringtail/lucas/backend/services.(*Store).List(0xc42000e170, 0x0, 0x0, 0xc420219ac8, 0x5f6ce8, 0x0)
	/src/github.com/ringtail/lucas/backend/services/store.go:73 +0x17a
github.com/ringtail/lucas/backend/services.(*Store).ListByPath(0xc42000e170, 0x0, 0x0, 0x3)
	/src/github.com/ringtail/lucas/backend/services/store.go:96 +0x64
github.com/ringtail/lucas/backend/handlers.StoreHandler(0xc6d3a0, 0xc42013d260, 0xc420238700)
	/src/github.com/ringtail/lucas/backend/handlers/storeHandler.go:34 +0x5ea
net/http.HandlerFunc.ServeHTTP(0x9e6818, 0xc6d3a0, 0xc42013d260, 0xc420238700)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420150a50, 0xc6d3a0, 0xc42013d260, 0xc420238700)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/ringtail/lucas/backend.(*LucasServer).Middleware.func1(0xc6d3a0, 0xc42013d260, 0xc42026a000)
	/src/github.com/ringtail/lucas/backend/backend.go:28 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc42013af80, 0xc6d3a0, 0xc42013d260, 0xc42026a000)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc4201520b0, 0xc6d3a0, 0xc42013d260, 0xc42026a000)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42023a0a0, 0xc6dbe0, 0xc420266280)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2018/12/13 05:54:53 http: panic serving 10.60.118.172:35076: runtime error: invalid memory address or nil pointer dereference

```

**Comment by ringtail** [comment]
麻烦贴下你的etcd启动参数

**Comment by ringtail** [comment]
@lateautumnlin

**Comment by ringtail** [comment]
另外，你是在master上进行部署的吗

**Comment by lateautumnlin** [comment]
大佬，可以了，刚才直接用了host网络才连通了，感谢
