### ISSUE TITLE
lucas can not get etcd key/value, error in logs

### ISSUE THREAD

**Issue by jackhuang007** [ringtail/lucas#8]
2020/01/13 07:30:26 http: panic serving 10.0.61.153:15182: runtime error: invalid memory address or nil pointer dereference
goroutine 3346 [running]:
net/http.(*conn).serve.func1(0xc42041a460)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x91d960, 0xca5f80)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/ringtail/lucas/backend/services.(*Store).List(0xc4201d6740, 0x0, 0x0, 0xc420397ac8, 0x5f6ce8, 0x0)
	/src/github.com/ringtail/lucas/backend/services/store.go:73 +0x17a
github.com/ringtail/lucas/backend/services.(*Store).ListByPath(0xc4201d6740, 0x0, 0x0, 0x3)
	/src/github.com/ringtail/lucas/backend/services/store.go:96 +0x64
github.com/ringtail/lucas/backend/handlers.StoreHandler(0xc6d3a0, 0xc4201a35e0, 0xc42041e300)
	/src/github.com/ringtail/lucas/backend/handlers/storeHandler.go:34 +0x5ea
net/http.HandlerFunc.ServeHTTP(0x9e6818, 0xc6d3a0, 0xc4201a35e0, 0xc42041e300)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc42012adb0, 0xc6d3a0, 0xc4201a35e0, 0xc42041e300)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/ringtail/lucas/backend.(*LucasServer).Middleware.func1(0xc6d3a0, 0xc4201a35e0, 0xc42041e200)
	/src/github.com/ringtail/lucas/backend/backend.go:28 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc4201231a0, 0xc6d3a0, 0xc4201a35e0, 0xc42041e200)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc420142160, 0xc6d3a0, 0xc4201a35e0, 0xc42041e200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42041a460, 0xc6dbe0, 0xc4203897c0)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

**Comment by ringtail** [comment]
duplicated #4

**Comment by ringtail** [comment]
update image version to registry.cn-hangzhou.aliyuncs.com/ringtail/lucas:0.0.2
